name: deploy-site

# Only run this when the master branch changes
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: github.repository == 'jbusecke/test_soeren'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Build the site
      - name: Build the site
        run: |
          jupyter-book build .

      - name: Zip the site
        run: |
          set -x
          set -e

          if [ -f site.zip ]; then
              rm -rf site.zip
          fi
          zip -r site.zip ./_build/html

      - uses: actions/upload-artifact@v2
        with:
          name: site-zip
          path: ./site.zip
#       # Push the site's HTML to github-pages (only if on main, previews are sent to netlify)
#       - name: Deploy to GitHub pages
#         if: github.ref == 'refs/heads/main'
#         uses: peaceiris/actions-gh-pages@v3.8.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./_build/html
#           enable_jekyll: false
#           # this is only for custom domains
          # cname: projectpythia.org
